In [1]:
import pandas as pd
import numpy as np

### Task 1 & 2

In [8]:
df = pd.read_csv('C:\\Users\\govar\\OneDrive\\Documents\\Data_Science_Journey\\data\\consultancy_data_5400.csv')
df.__len__

<bound method DataFrame.__len__ of       employee_id         full_name            department  \
0          670487   Patrick Sanchez  Engineering Delivery
1          146316     Megan Mcclain  Product Architecture
2           91161      Amanda Davis       Client Services
3          243962   Alyssa Gonzalez  Engineering Delivery
4          681453     Jennifer Cole  Engineering Delivery
...           ...               ...                   ...
5395        17844  Elizabeth Morrow  Engineering Delivery
5396       836591    Sophia Bennett           Design & UX
5397        23701       Clayton May           Design & UX
5398       370275    Danny Anderson           Design & UX
5399       428841     John Cardenas           Design & UX

                      position   level   hire_date           city    country  \
0          Associate Developer   entry  2023-03-26       New York        USA
1           Solution Architect     mid  2020-05-19         Berlin    Germany
2     Client Success Associate   entry  2023-07-22      Singapore  Singapore
3          Associate Developer   entry  2022-07-05      Singapore  Singapore
4                QA Engineer I   entry  2022-11-07       New York        USA
...                        ...     ...         ...            ...        ...
5395      Development Director  senior  2017-03-11  San Francisco        USA
5396               Design Lead     mid  2020-08-14       New York        USA
5397             UI Designer I   entry  2022-08-16      Singapore  Singapore
5398         Design Strategist     mid  2021-05-30       New York        USA
5399    Lead Design Strategist  senior  2014-01-28       New York        USA

        region  remote_work_ratio  travel_percentage  base_salary  \
0     Americas               24.7                1.8       132000
1         EMEA               37.3               18.8       176000
2         APAC               21.9               28.8        98000
3         APAC               23.2                4.5        98000
4     Americas               11.1                1.5       130000
...        ...                ...                ...          ...
5395  Americas               40.2               23.5       396000
5396  Americas               22.8               18.5       156000
5397      APAC               25.3                7.1       110000
5398  Americas               25.7               16.9       174000
5399  Americas               46.2               21.9       364000

      billing_rate  utilization_target  actual_utilization  \
0              250                  90                79.4
1              350                  68                67.4
2              150                  89                93.8
3              150                  90                93.6
4              250                  90                77.2
...            ...                 ...                 ...
5395           950                  70                67.5
5396           300                  77                65.4
5397           200                  82                72.6
5398           350                  77                68.9
5399          1050                  62                52.6

     primary_specialization secondary_specialization  \
0              Cloud Native             Cloud Native
1     Security Architecture    Security Architecture
2            Agile Delivery       Strategic Planning
3        Mobile Development       Mobile Development
4                  Frontend                 Frontend
...                     ...                      ...
5395     Mobile Development                  Backend
5396        Design Thinking            User Research
5397         Design Systems           Service Design
5398         Service Design            Mobile Design
5399          Mobile Design            Mobile Design

                                     industry_expertise  \
0                    Enterprise Software, Consumer Tech
1     HealthTech, Social Impact, Consumer Tech, Indu...
2                    Consumer Tech, FinTech, E-commerce
3                    Social Impact, Enterprise Software
4     Industrial Tech, HealthTech, Enterprise Softwa...
...                                                 ...
5395            Enterprise Software, EdTech, E-commerce
5396                           Industrial Tech, FinTech
5397  Enterprise Software, Industrial Tech, Social I...
5398           HealthTech, Enterprise Software, FinTech
5399         Industrial Tech, Social Impact, E-commerce

                                         certifications  performance_score  \
0                           Scrum Master, AWS Developer               3.65
1     Azure Architect, AWS Solutions Architect, Goog...               3.92
2                                                   PMP               3.01
3                           Azure Developer, Kubernetes               4.20
4                                          Scrum Master               3.42
...                                                 ...                ...
5395  Scrum Master, Kubernetes, AWS Developer, Azure...               3.33
5396                      Interaction Design Foundation               4.00
5397      Human Factors International, Google UX Design               3.48
5398                                   Google UX Design               4.02
5399      Human Factors International, Google UX Design               4.42

      innovation_score  delivery_quality  active_projects  \
0                 66.9              78.6                2
1                 90.0              86.3                3
2                 82.0              82.0                3
3                 71.3              83.1                2
4                 75.7              87.0                2
...                ...               ...              ...
5395              73.8              85.7                3
5396              80.1              89.8                2
5397              81.6              82.5                1
5398              69.0              80.2                1
5399              67.6              72.4                3

      avg_project_complexity  avg_project_duration  avg_team_size  \
0                        2.5                   8.5            5.5
1                        3.3                   9.7            7.0
2                        1.7                  10.0            4.7
3                        2.5                   4.0            4.5
4                        1.0                   3.0            7.0
...                      ...                   ...            ...
5395                     4.7                   4.3            6.3
5396                     1.5                  12.0            9.0
5397                     3.0                   4.0            3.0
5398                     2.0                   8.0            5.0
5399                     4.0                   6.7            4.7

      projects_on_time  project_satisfaction  training_hours  \
0                 80.1                   4.1              52
1                 60.0                   3.9              48
2                 86.0                   4.3              49
3                 74.8                   4.0              58
4                 74.7                   4.1              57
...                ...                   ...             ...
5395              60.0                   4.4              25
5396              87.3                   4.1              49
5397              78.4                   4.1              55
5398              82.2                   4.3              30
5399              86.5                   4.2             100

      mentorship_hours  knowledge_sharing_score  promotion_readiness  \
0                  -28                      4.5                 42.0
1                    3                      7.3                 79.6
2                  -23                      4.5                 35.3
3                  -12                      5.3                 42.9
4                  -15                      5.2                 37.1
...                ...                      ...                  ...
5395                39                      8.4                 11.8
5396                 0                      7.2                 73.6
5397               -26                      5.3                 43.8
5398                 3                      7.4                 61.4
5399                20                      9.4                 18.1

      engagement_score  flight_risk retention_risk  manager_id  total_comp  \
0                  6.9           29            Low    605912.0   132000.00
1                  8.2           42         Medium         NaN   176000.00
2                  6.9           40            Low    574842.0    98000.00
3                  8.0           38            Low    914277.0    98000.00
4                  8.0           27            Low    570871.0   130000.00
...                ...          ...            ...         ...         ...
5395               7.2           30            Low         NaN   396000.00
5396               7.0           27            Low         NaN   198432.62
5397               7.4           27            Low    520760.0   110000.00
5398               8.1           28            Low         NaN   174000.00
5399               9.3           30            Low         NaN   532394.97

      team_lead_projects  direct_reports  is_manager management_level  \
0                      0               0       False              NaN
1                      1               0       False              NaN
2                      0               0       False              NaN
3                      0               0       False              NaN
4                      0               0       False              NaN
...                  ...             ...         ...              ...
5395                   2               0       False              NaN
5396                   0               2        True              mid
5397                   0               0       False              NaN
5398                   0               0       False              NaN
5399                   2              10        True           senior

     span_of_control  management_premium  span_premium
0                NaN                0.00             0
1                NaN                0.00             0
2                NaN                0.00             0
3                NaN                0.00             0
4                NaN                0.00             0
...              ...                 ...           ...
5395             NaN                0.00             0
5396     Small (1-3)            34632.62          7800
5397             NaN                0.00             0
5398             NaN                0.00             0
5399      Large (7+)           113794.97         54600

[5400 rows x 44 columns]>

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5400 entries, 0 to 5399
Data columns (total 44 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   employee_id               5400 non-null   int64
 1   full_name                 5400 non-null   object
 2   department                5400 non-null   object
 3   position                  5400 non-null   object
 4   level                     5400 non-null   object
 5   hire_date                 5400 non-null   object
 6   city                      5400 non-null   object
 7   country                   5400 non-null   object
 8   region                    5400 non-null   object
 9   remote_work_ratio         5400 non-null   float64
 10  travel_percentage         5400 non-null   float64
 11  base_salary               5400 non-null   int64
 12  billing_rate              5400 non-null   int64
 13  utilization_target        5400 non-null   int64
 14  actual_utilization        5400 non-null   float64
 15  primary_specialization    5400 non-null   object
 16  secondary_specialization  5400 non-null   object
 17  industry_expertise        5400 non-null   object
 18  certifications            4718 non-null   object
 19  performance_score         5400 non-null   float64
 20  innovation_score          5400 non-null   float64
 21  delivery_quality          5400 non-null   float64
 22  active_projects           5400 non-null   int64
 23  avg_project_complexity    5400 non-null   float64
 24  avg_project_duration      5400 non-null   float64
 25  avg_team_size             5400 non-null   float64
 26  projects_on_time          5400 non-null   float64
 27  project_satisfaction      5400 non-null   float64
 28  training_hours            5400 non-null   int64
 29  mentorship_hours          5400 non-null   int64
 30  knowledge_sharing_score   5400 non-null   float64
 31  promotion_readiness       5400 non-null   float64
 32  engagement_score          5400 non-null   float64
 33  flight_risk               5400 non-null   int64
 34  retention_risk            5400 non-null   object
 35  manager_id                2777 non-null   float64
 36  total_comp                5400 non-null   float64
 37  team_lead_projects        5400 non-null   int64
 38  direct_reports            5400 non-null   int64
 39  is_manager                5400 non-null   bool
 40  management_level          496 non-null    object
 41  span_of_control           477 non-null    object
 42  management_premium        5400 non-null   float64
 43  span_premium              5400 non-null   int64
dtypes: bool(1), float64(17), int64(11), object(15)
memory usage: 1.8+ MB

In [10]:
df.min()

TypeError: '<=' not supported between instances of 'str' and 'float'